# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PlaceFinder' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
 pod 'GoogleMaps'
 pod 'AFNetworking', '~> 3.0'
  # Pods for PlaceFinder

  target 'PlaceFinderTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PlaceFinderUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
